### ISSUE TITLE
Is Late Show with Stephen Colbert not available on CBS

### ISSUE THREAD

**Issue by Patri-Ott** [plexinc-plugins/CBS.bundle#29]
Hi - I'm new here. Is there a version of the CBS bundle that still plays Colbert? I had a previous commit of the CBS bundle that played it until a couple of months ago. Now, the CBS plugin lists the Late Show with Stephen Colbert,but when I click it says the channel is not responding. Thanks for your help. - PO

**Comment by sander1** [comment]
Hi!

I just checked the channel and the Late Show with Stephen Colbert is listing fine over here. And playback of episodes also works. Please check your log files (`com.plexapp.plugins.cbs.log` and `com.plexapp.system.log`) and see if there is anything useful in there.

By the way, do other shows/episodes from this channel play on your setup?
