### ISSUE TITLE
Channel Not Responding

### ISSUE THREAD

**Issue by peterjohn123** [plexinc-plugins/CBS.bundle#30]
Now receiving **Channel Not Responding** after selecting any show episode.

Using Plex Server 1.9.7.4460. 

Channel has been removed and added. Server and host computer have been restart.

**Comment by cwgilbert** [comment]
Similar issue.  

From my roku plex app, I can log the plugin and select a show, but it won’t play anything

If I go to my windows pc which runs my plex server, when I try to play any episode, it says the plugin isnt responding.

**Comment by sander1** [comment]
Browsing the channel should work. Video playback is broken at the moment. See https://forums.plex.tv/discussion/comment/1660404/#Comment_1660404

**Comment by sander1** [comment]
URL Service just got updated: https://github.com/plexinc-plugins/Services.bundle/commit/5c629c09cbd4cbc6105ffe6c6d2cacc2a50784dc
